version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wallet_user
      DB_PASSWORD: wallet_password
      DB_NAME: wallet_db
      DB_SSLMODE: disable

volumes:
  db_data: